## Here is the optional activity slide:
![activity_diagram](optional_activity.png)

#### In order to properly create the representation matrix needed. I followed a similar approach to the representation matrix from the 'Cat and mouse' activity. The step was for me to etablish numerical labels for each room of the house (including street and backyard).

![activity_diagram](RL_optional_drawn.png)

#### From there I established (first in human language) the rules of the room transitions:
- Street: '0'. You can only move to room 1 from the street
- Room 1: '1' You can only move to rooms 5,2 or back to 0 from room 1
- Room 2:  '2' you can only move to rooms 1, 4 and 4 from room 2
- Room 3: '3' you can only move to room 2 from room 3
- Room 4: '4' you can only move room 2 or backyard (6) (backyard is the goal)
- room 5: '5' You can only move to room from room 5
- Room 6 (backyard): absorbing state

### Following this, we can represent the transition matrix as follows:

In [1]:
import numpy as np

# Transition matrix
# each row represents a room state
M = np.array([
    [0, 1, 0, 0, 0, 0, 0],  # From Street (0) to Room 1
    [1, 0, 1, 0, 1, 0, 0],  # From Room 1 to Room 2, Room 5 or back to street (0)
    [0, 1, 0, 1, 1, 0, 0],  # From Room 2 to Room 1, Room 3, and Room 4
    [0, 0, 1, 0, 0, 0, 0],  # From Room 3 to Room 2
    [0, 0, 1, 0, 0, 0, 1],  # From Room 4 to Backyard (6) or back to 2
    [0, 1, 0, 0, 0, 0, 0],  # From Room 5 to Room 1
    [0, 0, 0, 0, 0, 0, 1],  # Backyard (6) is an absorbing state, once entered it doesn't transition out
])

print(M)

[[0 1 0 0 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]]
